# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.10.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/evan/desktop/xpwn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/evan/desktop/xpwn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/evan/desktop/xpwn/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/evan/desktop/xpwn/CMakeFiles /Users/evan/desktop/xpwn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/evan/desktop/xpwn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f common/CMakeFiles/common.dir/build.make common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named minizip

# Build rule for target.
minizip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minizip
.PHONY : minizip

# fast build rule for target.
minizip/fast:
	$(MAKE) -f minizip/CMakeFiles/minizip.dir/build.make minizip/CMakeFiles/minizip.dir/build
.PHONY : minizip/fast

#=============================================================================
# Target rules for targets named dmg

# Build rule for target.
dmg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dmg
.PHONY : dmg

# fast build rule for target.
dmg/fast:
	$(MAKE) -f dmg/CMakeFiles/dmg.dir/build.make dmg/CMakeFiles/dmg.dir/build
.PHONY : dmg/fast

#=============================================================================
# Target rules for targets named dmg-bin

# Build rule for target.
dmg-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dmg-bin
.PHONY : dmg-bin

# fast build rule for target.
dmg-bin/fast:
	$(MAKE) -f dmg/CMakeFiles/dmg-bin.dir/build.make dmg/CMakeFiles/dmg-bin.dir/build
.PHONY : dmg-bin/fast

#=============================================================================
# Target rules for targets named hdutil

# Build rule for target.
hdutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdutil
.PHONY : hdutil

# fast build rule for target.
hdutil/fast:
	$(MAKE) -f hdutil/CMakeFiles/hdutil.dir/build.make hdutil/CMakeFiles/hdutil.dir/build
.PHONY : hdutil/fast

#=============================================================================
# Target rules for targets named hfs

# Build rule for target.
hfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hfs
.PHONY : hfs

# fast build rule for target.
hfs/fast:
	$(MAKE) -f hfs/CMakeFiles/hfs.dir/build.make hfs/CMakeFiles/hfs.dir/build
.PHONY : hfs/fast

#=============================================================================
# Target rules for targets named hfsplus

# Build rule for target.
hfsplus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hfsplus
.PHONY : hfsplus

# fast build rule for target.
hfsplus/fast:
	$(MAKE) -f hfs/CMakeFiles/hfsplus.dir/build.make hfs/CMakeFiles/hfsplus.dir/build
.PHONY : hfsplus/fast

#=============================================================================
# Target rules for targets named imagetool

# Build rule for target.
imagetool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imagetool
.PHONY : imagetool

# fast build rule for target.
imagetool/fast:
	$(MAKE) -f ipsw-patch/CMakeFiles/imagetool.dir/build.make ipsw-patch/CMakeFiles/imagetool.dir/build
.PHONY : imagetool/fast

#=============================================================================
# Target rules for targets named ipsw

# Build rule for target.
ipsw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ipsw
.PHONY : ipsw

# fast build rule for target.
ipsw/fast:
	$(MAKE) -f ipsw-patch/CMakeFiles/ipsw.dir/build.make ipsw-patch/CMakeFiles/ipsw.dir/build
.PHONY : ipsw/fast

#=============================================================================
# Target rules for targets named libXPwn.a

# Build rule for target.
libXPwn.a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libXPwn.a
.PHONY : libXPwn.a

# fast build rule for target.
libXPwn.a/fast:
	$(MAKE) -f ipsw-patch/CMakeFiles/libXPwn.a.dir/build.make ipsw-patch/CMakeFiles/libXPwn.a.dir/build
.PHONY : libXPwn.a/fast

#=============================================================================
# Target rules for targets named xpwn

# Build rule for target.
xpwn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xpwn
.PHONY : xpwn

# fast build rule for target.
xpwn/fast:
	$(MAKE) -f ipsw-patch/CMakeFiles/xpwn.dir/build.make ipsw-patch/CMakeFiles/xpwn.dir/build
.PHONY : xpwn/fast

#=============================================================================
# Target rules for targets named xpwntool

# Build rule for target.
xpwntool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xpwntool
.PHONY : xpwntool

# fast build rule for target.
xpwntool/fast:
	$(MAKE) -f ipsw-patch/CMakeFiles/xpwntool.dir/build.make ipsw-patch/CMakeFiles/xpwntool.dir/build
.PHONY : xpwntool/fast

#=============================================================================
# Target rules for targets named applmobile

# Build rule for target.
applmobile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 applmobile
.PHONY : applmobile

# fast build rule for target.
applmobile/fast:
	$(MAKE) -f pwnmetheus2/CMakeFiles/applmobile.dir/build.make pwnmetheus2/CMakeFiles/applmobile.dir/build
.PHONY : applmobile/fast

#=============================================================================
# Target rules for targets named dripwn

# Build rule for target.
dripwn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dripwn
.PHONY : dripwn

# fast build rule for target.
dripwn/fast:
	$(MAKE) -f dripwn/CMakeFiles/dripwn.dir/build.make dripwn/CMakeFiles/dripwn.dir/build
.PHONY : dripwn/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... common"
	@echo "... minizip"
	@echo "... dmg"
	@echo "... dmg-bin"
	@echo "... hdutil"
	@echo "... hfs"
	@echo "... hfsplus"
	@echo "... imagetool"
	@echo "... ipsw"
	@echo "... libXPwn.a"
	@echo "... xpwn"
	@echo "... xpwntool"
	@echo "... applmobile"
	@echo "... dripwn"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

